FROM openjdk:11
ADD ./target/eurekadiscoverymicroservice-0.0.1-SNAPSHOT.jar /usr/src/eurekadiscoverymicroservice-0.0.1-SNAPSHOT.jar
WORKDIR usr/src
ENTRYPOINT ["java","-jar", "eurekadiscoverymicroservice-0.0.1-SNAPSHOT.jar"]